package GameMaster;

public enum GamePhaseState {
    WAITING_FOR_WELCOME,
    WAITING_FOR_TWO_SHALL_ENTER,
    WAITING_FOR_TOURNAMENT_TO_BEGIN_WITH_PID,
    WAITING_FOR_CHALLENGE,
    WAITING_FOR_ROUND_TO_BEGIN,
    IN_ROUND
}
